[CmdletBinding()]param([switch]$InjectWorkerFailure,[switch]$InjectPublishInterruption)
$ErrorActionPreference='Stop'
$here=Split-Path -Parent $MyInvocation.MyCommand.Path
$lockPath=Join-Path $here '.publish.lock'
$lock=[IO.File]::Open($lockPath,[IO.FileMode]::OpenOrCreate,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None)
function Cx([double]$re,[double]$im){[Numerics.Complex]::new($re,$im)}
function Green([double]$x,[double]$xs,[double]$f,[double]$sigma,[double]$mu){
 $r=[Math]::Abs($x-$xs);if($r-le0){throw'singular geometry'};$k=[Numerics.Complex]::Sqrt($(Cx 0 (2*[Math]::PI*$f*$mu*$sigma)));[Numerics.Complex]::Exp(-$k*$r)/(2*[Math]::PI*$sigma*$r)
}
function CsamtEKernel([double]$x,[double]$xs,[double]$h,[double]$f,[double]$sigma,[double]$mu){$dx=$x-$xs;$r=[Math]::Sqrt($dx*$dx+$h*$h);$k=[Numerics.Complex]::Sqrt($(Cx 0 (2*[Math]::PI*$f*$mu*$sigma)));$dx/$r*[Numerics.Complex]::Exp(-$k*$r)/(2*[Math]::PI*$sigma)*($k/$r+1/($r*$r))}
function CsamtHKernel([double]$x,[double]$xs,[double]$h,[double]$f,[double]$sigma,[double]$mu){$dx=$x-$xs;$r=[Math]::Sqrt($dx*$dx+$h*$h);$k=[Numerics.Complex]::Sqrt($(Cx 0 (2*[Math]::PI*$f*$mu*$sigma)));$h*[Numerics.Complex]::Exp(-$k*$r)/(4*[Math]::PI*$r*$r*$r)*(1+$k*$r)}
function FinitePositive($v){try{$d=[double]$v;return [double]::IsFinite($d)-and$d-gt0}catch{return $false}}
function ResolveUnder([string]$root,[string]$leaf){
 $rootFull=[IO.Path]::GetFullPath($root).TrimEnd('\');$candidate=[IO.Path]::GetFullPath((Join-Path $rootFull $leaf))
 if(-not$candidate.StartsWith($rootFull+'\',[StringComparison]::OrdinalIgnoreCase)){throw'path escapes versions root'};return $candidate
}
try{
 $journal=Join-Path $here '.publish-journal.json';if(Test-Path $journal){$old=gc -Raw -LiteralPath $journal|ConvertFrom-Json;$names=@($old.PSObject.Properties.Name);if($names.Count-ne2-or-not($names-ccontains'schema')-or-not($names-ccontains'version_path')-or$old.schema-cne'wp3-publish-journal-v1'){throw'invalid publish journal schema'};$vp=[string]$old.version_path;if($vp-cnotmatch'^versions/([0-9]{8}T[0-9]{9}Z-[0-9a-f]{32})$'){throw'invalid publish journal version path'};$versionId=$Matches[1];$versionsRoot=Join-Path $here 'versions';$candidate=ResolveUnder $versionsRoot $versionId;$active=gc -Raw -LiteralPath (Join-Path $here 'active-output.json')|ConvertFrom-Json;if($active.version_path-ceq$vp){throw'publish journal targets active version'};if(Test-Path -LiteralPath $candidate){Remove-Item -Recurse -Force -LiteralPath $candidate};Remove-Item -Force -LiteralPath $journal}
 $cfg=Get-Content -Raw (Join-Path $here 'config.json')|ConvertFrom-Json;$ct=Get-Content -Raw (Join-Path $here 'physics-contract.json')|ConvertFrom-Json
 if(@($cfg.rock_fixture.PSObject.Properties.Name|Where-Object{$_-match'(?i)temperature_c|celsius|degc'}).Count-gt0){throw'machine temperature must use kelvin fields'}
 if($cfg.tem.PSObject.Properties.Name-ccontains'characteristic_loop_length_m'){throw'characteristic loop length is derived, not configurable'}
 foreach($v in @($cfg.medium.sigma_s_m,$cfg.medium.epsilon_f_m,$cfg.medium.mu_h_m,$cfg.tem.current_a,$cfg.tem.equivalent_transmitter_area_m2,$cfg.tem.equivalent_receiver_area_m2,$cfg.tem.transmitter_turns,$cfg.tem.receiver_turns,$cfg.tem.loop_depth_m,$cfg.tem.ramp_s,$cfg.tem.gate_quadrature_order,$cfg.tem.small_loop_domain.ratio_max,$cfg.csamt.frequency_hz,$cfg.csamt.current_a,$cfg.csamt.electrode_depth_m,$cfg.csamt.source_depth_m,$cfg.csamt.receiver_z_m,$cfg.wfem.frequency_hz,$cfg.wfem.current_a,$cfg.dc.rho_ohm_m,$cfg.dc.current_a,$cfg.dc.am_m,$cfg.dc.an_m,$cfg.dc.bm_m,$cfg.dc.bn_m,$cfg.mt.rho_ohm_m,$cfg.mt.frequency_hz,$cfg.rock_fixture.temperature_k,$cfg.rock_fixture.curie_temperature_k,$cfg.rock_fixture.confining_pressure_pa,$cfg.rock_fixture.pore_pressure_pa)){if(-not(FinitePositive $v)){throw'nonpositive/nonfinite physical input'}}
 foreach($v in @($cfg.csamt.a_m,$cfg.csamt.b_m,$cfg.wfem.a_m,$cfg.wfem.b_m,$cfg.wfem.m_m,$cfg.wfem.n_m)){if(-not[double]::IsFinite([double]$v)){throw'nonfinite geometry'}}
 if([double]$cfg.rock_fixture.biot_alpha-lt0-or[double]$cfg.rock_fixture.biot_alpha-gt1-or-not[double]::IsFinite([double]$cfg.rock_fixture.biot_alpha)){throw'invalid Biot alpha'}
 foreach($q in @($cfg.tem.quadrature_levels+$cfg.csamt.quadrature_levels)){if([int]$q-lt2-or[double]$q-ne[int]$q){throw'invalid integration level'}}
 if($cfg.tem.gates_s.Count-ne$cfg.tem.times_s.Count-or[int]$cfg.tem.gate_quadrature_order-lt2){throw'invalid TEM gates'};foreach($g in $cfg.tem.gates_s){if($g.Count-ne2-or-not[double]::IsFinite([double]$g[0])-or-not[double]::IsFinite([double]$g[1])-or[double]$g[0]-le[double]$cfg.tem.ramp_s-or[double]$g[1]-le[double]$g[0]){throw'invalid TEM gate bounds'}}
 foreach($x in $cfg.csamt.receiver_x_m){if(-not[double]::IsFinite([double]$x)-or[double]$x-le[double]$cfg.csamt.b_m){throw'invalid CSAMT receiver distance'}}
 foreach($b in @('induced_dominant','magnetization_known','low_latitude','stable_strike','local_threshold_calibrated')){if($cfg.decisions.$b-isnot[bool]){throw"invalid boolean $b"}};if($cfg.decisions.mt_dimension-notin@('2d','3d')){throw'invalid MT dimension'};if([int]$cfg.decisions.competing_explanations_count-lt0){throw'invalid competing explanation count'}
 if([double]$cfg.tem.ramp_s-le0-or($cfg.tem.times_s|?{[double]$_-le[double]$cfg.tem.ramp_s})){throw'invalid TEM time/ramp'}
  if([double]$cfg.csamt.a_m-eq[double]$cfg.csamt.b_m-or[double]$cfg.wfem.a_m-eq[double]$cfg.wfem.b_m-or[double]$cfg.wfem.m_m-eq[double]$cfg.wfem.n_m){throw'degenerate geometry'}
 if(@($cfg.tem.times_s|Where-Object{-not[double]::IsFinite([double]$_)-or[double]$_-le0}).Count-gt0){throw'invalid TEM time'}
 if($cfg.csamt.source_direction-ne'+x'-or$cfg.wfem.source_direction-ne'+x'-or$cfg.wfem.receiver-ne'finite_axial_electric_bipole'-or$cfg.wfem.polarity-ne'empymod_A_to_B_equals_B_injection_A_return'){throw'device/direction/polarity enum'}
 $m=1/(1+[Math]::Exp(-[double]$cfg.rock_fixture.tdip_logit));$tau=[Math]::Exp([double]$cfg.rock_fixture.tau_log_s);$se=[double]$cfg.rock_fixture.confining_pressure_pa-[double]$cfg.rock_fixture.biot_alpha*[double]$cfg.rock_fixture.pore_pressure_pa
 if(-not[double]::IsFinite($m)-or-not[double]::IsFinite($tau)-or-not[double]::IsFinite($se)-or-not($m-gt0-and$m-lt1-and$tau-gt0-and$se-ge0)){throw'rock fixture domain'};if([double]$cfg.rock_fixture.temperature_k-le0-or[double]$cfg.rock_fixture.curie_temperature_k-le0){throw'temperature domain'}
 $ratio=[double]$cfg.medium.sigma_s_m/(2*[Math]::PI*[double]$cfg.csamt.frequency_hz*[double]$cfg.medium.epsilon_f_m);if($ratio-lt[double]$ct.diffusion.conductive_ratio_min){throw'diffusion approximation rejected before kernel evaluation'};$tMin=[double](($cfg.tem.gates_s|%{[double]$_[0]}|Measure-Object -Minimum).Minimum);$deltaDiff=[Math]::Sqrt(4*$tMin/([double]$cfg.medium.mu_h_m*[double]$cfg.medium.sigma_s_m));$txLength=[Math]::Sqrt([double]$cfg.tem.equivalent_transmitter_area_m2/[Math]::PI);$rxLength=[Math]::Sqrt([double]$cfg.tem.equivalent_receiver_area_m2/[Math]::PI);$loopLength=[Math]::Max($txLength,$rxLength);$loopRatio=$loopLength/$deltaDiff;if($cfg.tem.device-ne'magnetic_dipole_small_loop_approximation'-or$cfg.tem.small_loop_domain.diffusion_length_definition-ne'sqrt(4*t/(mu*sigma))'-or$cfg.tem.small_loop_domain.ratio_definition-ne'max(sqrt(A_tx/pi),sqrt(A_rx/pi))/delta_diff(t_min)'-or-not(FinitePositive $cfg.tem.small_loop_domain.ratio_max)-or-not[double]::IsFinite($loopRatio)-or$loopRatio-gt[double]$cfg.tem.small_loop_domain.ratio_max){throw'TEM small-loop approximation domain rejected before empymod'};$branch='diffusion'
 $id=([DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ')+'-'+[guid]::NewGuid().ToString('N'));$stage=Join-Path $here ('.stage-'+[guid]::NewGuid().ToString('N'));$stageFull=[IO.Path]::GetFullPath($stage);if([IO.Path]::GetFullPath((Split-Path -Parent $stageFull)).TrimEnd('\')-ne[IO.Path]::GetFullPath($here).TrimEnd('\')-or[IO.Path]::GetFileName($stageFull)-notmatch'^\.stage-[0-9a-f]{32}$'){throw'unauthorized stage path'};New-Item -ItemType Directory $stageFull|Out-Null;$stage=$stageFull
 try{
  if($InjectWorkerFailure){throw'injected worker failure'}
  $sigma=[double]$cfg.medium.sigma_s_m;$mu=[double]$cfg.medium.mu_h_m
  $dc=[double]$cfg.dc.rho_ohm_m/(2*[Math]::PI)*(1/[double]$cfg.dc.am_m-1/[double]$cfg.dc.an_m-1/[double]$cfg.dc.bm_m+1/[double]$cfg.dc.bn_m)
  $mt=[Numerics.Complex]::Sqrt($(Cx 0 (2*[Math]::PI*[double]$cfg.mt.frequency_hz*$mu*[double]$cfg.mt.rho_ohm_m)))
  $moment=[double]$cfg.tem.transmitter_turns*[double]$cfg.tem.equivalent_transmitter_area_m2*[double]$cfg.tem.current_a;$mr=[double]$cfg.tem.receiver_turns*[double]$cfg.tem.equivalent_receiver_area_m2
  $cc=($moment*$mr*[Math]::Pow($mu,2.5)*[Math]::Pow($sigma,1.5))/(20*[Math]::Pow([Math]::PI,1.5));$tem=@()
  foreach($t0 in $cfg.tem.times_s){$t=[double]$t0;$step=-$cc*[Math]::Pow($t,-2.5);$levels=@();foreach($n0 in $cfg.tem.quadrature_levels){$n=[int]$n0;$sum=0.;for($j=0;$j-lt$n;$j++){$u=([double]$cfg.tem.ramp_s)*($j+.5)/$n;$sum+=(-$cc*[Math]::Pow($t-$u,-2.5))};$levels+=($sum/[double]$n)};$tem+=,[ordered]@{time_s=$t;step_v=$step;ramp_levels_v=$levels;ramp_qoi_v=$levels[-1]}}
  $cs=@();foreach($x0 in $cfg.csamt.receiver_x_m){$x=[double]$x0;$els=@();$hls=@();foreach($n0 in $cfg.csamt.quadrature_levels){$n=[int]$n0;$dx=([double]$cfg.csamt.b_m-[double]$cfg.csamt.a_m)/$n;$sumE=Cx 0 0;$sumH=Cx 0 0;for($j=0;$j-lt$n;$j++){$xs=[double]$cfg.csamt.a_m+($j+.5)*$dx;$sumE+=(CsamtEKernel $x $xs ([double]$cfg.csamt.source_depth_m) ([double]$cfg.csamt.frequency_hz) $sigma $mu)*$dx;$sumH+=(CsamtHKernel $x $xs ([double]$cfg.csamt.source_depth_m) ([double]$cfg.csamt.frequency_hz) $sigma $mu)*$dx};$e=-[double]$cfg.csamt.current_a*$sumE/([double]$cfg.csamt.b_m-[double]$cfg.csamt.a_m);$h=[double]$cfg.csamt.current_a*$sumH/([double]$cfg.csamt.b_m-[double]$cfg.csamt.a_m);$els+=,$e;$hls+=,$h};$e=$els[-1];$h=$hls[-1];$cs+=,[ordered]@{x_m=$x;region=if($x-lt300){'near'}elseif($x-lt1200){'transition'}else{'far'};ex=@{re=$e.Real;im=$e.Imaginary};hy=@{re=$h.Real;im=$h.Imaginary};ex_levels=@($els|%{@{re=$_.Real;im=$_.Imaginary}});hy_levels=@($hls|%{@{re=$_.Real;im=$_.Imaginary}});rho_a=[Math]::Pow($e.Magnitude/$h.Magnitude,2)/(2*[Math]::PI*[double]$cfg.csamt.frequency_hz*$mu);phase_rad=($e/$h).Phase}}
  $gmA=Green ([double]$cfg.wfem.m_m) ([double]$cfg.wfem.a_m) ([double]$cfg.wfem.frequency_hz) $sigma $mu;$gmB=Green ([double]$cfg.wfem.m_m) ([double]$cfg.wfem.b_m) ([double]$cfg.wfem.frequency_hz) $sigma $mu
  $gnA=Green ([double]$cfg.wfem.n_m) ([double]$cfg.wfem.a_m) ([double]$cfg.wfem.frequency_hz) $sigma $mu;$gnB=Green ([double]$cfg.wfem.n_m) ([double]$cfg.wfem.b_m) ([double]$cfg.wfem.frequency_hz) $sigma $mu;$wf=($gmA-$gmB)-($gnA-$gnB)
  $wfDc=((Green ([double]$cfg.wfem.m_m) ([double]$cfg.wfem.a_m) 0 $sigma $mu)-(Green ([double]$cfg.wfem.m_m) ([double]$cfg.wfem.b_m) 0 $sigma $mu))-((Green ([double]$cfg.wfem.n_m) ([double]$cfg.wfem.a_m) 0 $sigma $mu)-(Green ([double]$cfg.wfem.n_m) ([double]$cfg.wfem.b_m) 0 $sigma $mu))
  $den=1/[Math]::Abs([double]$cfg.wfem.m_m-[double]$cfg.wfem.a_m)-1/[Math]::Abs([double]$cfg.wfem.n_m-[double]$cfg.wfem.a_m)-1/[Math]::Abs([double]$cfg.wfem.m_m-[double]$cfg.wfem.b_m)+1/[Math]::Abs([double]$cfg.wfem.n_m-[double]$cfg.wfem.b_m);if([Math]::Abs($den)-lt1e-15){throw'degenerate WFEM geometric factor'};$kAxial=2*[Math]::PI/$den;$app=$kAxial*$wf
  $legacy=[ordered]@{tem=$tem;csamt=$cs;wfem=@{re=$wf.Real;im=$wf.Imaginary}}
  $oraclePy=Join-Path $here '.venv-oracle/Scripts/python.exe';$oracleScript=Join-Path $here 'oracle/empymod-frequency-oracle.py';if(-not(Test-Path $oraclePy)-or-not(Test-Path $oracleScript)){throw'empymod oracle environment missing'};$empPath=Join-Path $stage 'empymod-reference.json';& $oraclePy $oracleScript --config (Join-Path $here 'config.json') --output $empPath *> $null;if($LASTEXITCODE-ne0-or-not(Test-Path $empPath)){throw'empymod oracle execution failed'};$emp=Get-Content -Raw $empPath|ConvertFrom-Json;if($emp.empymod_version-ne'2.6.0'){throw'empymod version mismatch'}
  $tem=@($emp.tem_magnetic_dipole_small_loop_gate_average|%{[ordered]@{gate_start_s=$_.start_s;gate_stop_s=$_.stop_s;step_gate_average_v=$_.step_gate_average_v;ramp_gate_average_v=$_.ramp_gate_average_v;nodes_s=$_.nodes_s;weights=$_.weights}})
  $temAsym=@($emp.tem_magnetic_dipole_late_time_asymptotic_gate_average|%{[ordered]@{gate_start_s=$_.start_s;gate_stop_s=$_.stop_s;step_gate_average_v=$_.step_gate_average_v;ramp_gate_average_v=$_.ramp_gate_average_v;nodes_s=$_.nodes_s;weights=$_.weights}})
  $cs=@($emp.csamt|%{[ordered]@{x_m=$_.x_m;region=if([double]$_.x_m-lt300){'near'}elseif([double]$_.x_m-lt2000){'transition'}else{'far'};ex=$_.ex;hy=$_.hy;rho_a=$_.rho_a_ohm_m;phase_rad=$_.phase_rad}})
  $wf=Cx ([double]$emp.wfem_delta_u_over_i_ohm.dlf.re) ([double]$emp.wfem_delta_u_over_i_ohm.dlf.im);$app=$kAxial*$wf
   [ordered]@{reference_engine='empymod==2.6.0/dlf';tem_device='magnetic-dipole/small-loop approximation';small_loop_domain=@{t_min_s=$tMin;delta_diff_m=$deltaDiff;tx_characteristic_length_m=$txLength;rx_characteristic_length_m=$rxLength;characteristic_loop_length_m=$loopLength;ratio=$loopRatio;ratio_max=[double]$cfg.tem.small_loop_domain.ratio_max};dc=@{re=$dc;im=0;unit='ohm'};mt=@{re=$mt.Real;im=$mt.Imaginary;unit='ohm'};tem=$tem;tem_asymptotic=$temAsym;csamt=$cs;wfem=@{re=$wf.Real;im=$wf.Imaginary;unit='ohm';geometric_factor_m=$kAxial;apparent_complex=@{re=$app.Real;im=$app.Imaginary;unit='ohm_m'};rho_a_ohm_m=$app.Magnitude;phase_rad=$app.Phase};diagnostic_legacy=$legacy}|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 (Join-Path $stage 'raw-responses.json')
  $rtp=if($cfg.decisions.induced_dominant-and$cfg.decisions.magnetization_known-and-not$cfg.decisions.low_latitude){'publish_rtp'}else{'alternative_magnetization'};$mtDecision=if($cfg.decisions.mt_dimension-eq'2d'-and$cfg.decisions.stable_strike){'publish_2d'}else{'publish_3d_tensor'};$thr=if($cfg.decisions.local_threshold_calibrated-and[int]$cfg.decisions.competing_explanations_count-ge1){'publish_calibrated'}else{'local_calibration_required'}
  [ordered]@{run_id=$cfg.run_id;status='Passed';evidence_class=$cfg.evidence_class;branch=@{conductive_ratio=$ratio;solver=$branch};rock=@{m=$m;tau_s=$tau;effective_stress_pa=$se;curie_branch=if([double]$cfg.rock_fixture.temperature_k-gt[double]$cfg.rock_fixture.curie_temperature_k){'curie_weiss'}else{'mineral_calibration'}};decisions=@{rtp=$rtp;mt=$mtDecision;threshold=$thr}}|ConvertTo-Json -Depth 6|Set-Content -Encoding utf8 (Join-Path $stage 'results.json')
  Copy-Item (Join-Path $here 'config.json') $stage;Copy-Item (Join-Path $here 'physics-contract.json') $stage
  $hash=[ordered]@{};Get-ChildItem $stage -File|Sort Name|%{$hash[$_.Name]=(Get-FileHash -Algorithm SHA256 $_.FullName).Hash.ToLowerInvariant()}
  $src=[ordered]@{};foreach($s in @('config.json','physics-contract.json','run-wp3-physics.ps1','oracle/wp3-oracle.ps1','oracle/empymod-frequency-oracle.py','oracle/requirements-lock.txt','oracle/EMPYMOD-PROVENANCE.md')){$src[$s]=(Get-FileHash -Algorithm SHA256 (Join-Path $here $s)).Hash.ToLowerInvariant()}
  [ordered]@{schema='wp3-manifest-v2';run_id=$cfg.run_id;run_instance_id=$id;evidence_class=$cfg.evidence_class;status='Passed';files=$hash;sources=$src}|ConvertTo-Json -Depth 8|Set-Content -Encoding utf8 (Join-Path $stage 'manifest.json')
  $versions=Join-Path $here 'versions';New-Item -ItemType Directory -Force $versions|Out-Null;$dest=Join-Path $versions $id;Move-Item $stage $dest
  $jtmp=Join-Path $here ('.journal-'+[guid]::NewGuid().ToString('N')+'.tmp');$jb=[Text.Encoding]::UTF8.GetBytes(([ordered]@{schema='wp3-publish-journal-v1';version_path=('versions/'+$id)}|ConvertTo-Json));$jf=[IO.File]::Open($jtmp,'CreateNew','Write','None');$jf.Write($jb);$jf.Flush($true);$jf.Dispose();Move-Item -Force $jtmp $journal
  if($InjectPublishInterruption){throw'injected publish interruption'}
  $mh=(Get-FileHash -Algorithm SHA256 (Join-Path $dest 'manifest.json')).Hash.ToLowerInvariant();$ptr=[ordered]@{schema='wp3-active-output-v1';run_instance_id=$id;version_path=('versions/'+$id);manifest_sha256=$mh}
  $tmp=Join-Path $here ('active-output.'+[guid]::NewGuid().ToString('N')+'.tmp');$json=$ptr|ConvertTo-Json;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$fs=[IO.File]::Open($tmp,'CreateNew','Write','None');$fs.Write($bytes);$fs.Flush($true);$fs.Dispose();$active=Join-Path $here 'active-output.json';if(Test-Path $active){$bak=Join-Path $here ('active-output.'+[guid]::NewGuid().ToString('N')+'.bak');[IO.File]::Replace($tmp,$active,$bak,$true);Remove-Item -Force $bak}else{Move-Item $tmp $active};Remove-Item -Force $journal
  "PASS run_id=$($cfg.run_id) version=$id"
 }finally{if(Test-Path $stage){Remove-Item -Recurse -Force $stage}}
}finally{$lock.Dispose()}
