[CmdletBinding()]param([switch]$SelfTest,[string]$OutputOverride='',[switch]$SkipSignoff)
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $MyInvocation.MyCommand.Path;$toy=Join-Path $root 'validation/wp3-physics'
function Bad($m){throw "WP3 validation failed: $m"};function Req($c,$m){if(-not$c){Bad $m}}
function Near($a,$b,$rt,$at=1e-14){[Math]::Abs([double]$a-[double]$b)-le([double]$at+[double]$rt*[Math]::Abs([double]$b))}
function LogSlope($rows,$indices){$sx=0.0;$sy=0.0;$sxx=0.0;$sxy=0.0;$n=$indices.Count;foreach($i in $indices){$x=[Math]::Log(.5*([double]$rows[$i].gate_start_s+[double]$rows[$i].gate_stop_s));$y=[Math]::Log([Math]::Abs([double]$rows[$i].step_gate_average_v));$sx+=$x;$sy+=$y;$sxx+=$x*$x;$sxy+=$x*$y};return($n*$sxy-$sx*$sy)/($n*$sxx-$sx*$sx)}
function ReadJsonRetry($path){for($i=0;$i-lt20;$i++){try{return Get-Content -Raw -LiteralPath $path|ConvertFrom-Json}catch{if($i-eq19){throw};Start-Sleep -Milliseconds 10}}}
function FinitePositive($v){try{$d=[double]$v;return [double]::IsFinite($d)-and$d-gt0}catch{return $false}}
function ReadSignoffRoot($path){
 $expected=@('01-引言.md','02-全方法深度融合的底层逻辑与理论总纲.md','06-合成数据验证方案与验收设计.md','附录1-分矿种多方法融合定制化勘查模板.md','附录11-分勘查阶段标准化操作手册.md','附录13-岩性物性参数统计数据库.md','附录14-地质先验知识库.md','validation/wp3-physics/config.json','validation/wp3-physics/physics-contract.json','validation/wp3-physics/run-wp3-physics.ps1','validation/wp3-physics/oracle/wp3-oracle.ps1','validate-wp3.ps1','ACTIVE_MANIFEST')
 $all=@(Get-Content -LiteralPath $path);Req($all.Count-eq15-and$all[0]-ceq'# WP3 signoff input root v1'-and$all[1]-ceq'# SHA-256, UTF-8 path order fixed below')'signoff root header/line count'
 $lines=@($all[2..14]);for($i=0;$i-lt$expected.Count;$i++){Req($lines[$i]-cmatch'^([0-9a-f]{64})  (.+)$')"signoff root syntax $i";Req($Matches[2]-ceq$expected[$i])"signoff root member/order $i"}
 return $lines
}
function ParseSignoff($text){
 $keys=@('状态','输入版本','manifest SHA-256','成员清单内容根SHA-256','根清单文件SHA-256');$result=@{}
 foreach($key in $keys){$matches=[regex]::Matches($text,'(?m)^- '+[regex]::Escape($key)+'：(?:`([^`\r\n]+)`|([^`\r\n]+))\s*$');Req($matches.Count-eq1)"signoff field unique $key";$result[$key]=if($matches[0].Groups[1].Success){$matches[0].Groups[1].Value}else{$matches[0].Groups[2].Value.Trim()}}
 return $result
}
if($OutputOverride){$out=$OutputOverride}else{$p=ReadJsonRetry (Join-Path $toy 'active-output.json');Req($p.schema-eq'wp3-active-output-v1')'pointer schema';Req($p.version_path-match'^versions/[0-9]{8}T[0-9]{9}Z-[0-9a-f]{32}$')'pointer path';$out=[IO.Path]::GetFullPath((Join-Path $toy $p.version_path));$vr=[IO.Path]::GetFullPath((Join-Path $toy 'versions')).TrimEnd('\')+'\';Req($out.StartsWith($vr,[StringComparison]::OrdinalIgnoreCase))'pointer escape';Req((Get-FileHash -Algorithm SHA256 (Join-Path $out 'manifest.json')).Hash.ToLowerInvariant()-eq$p.manifest_sha256)'pointer hash'}
$cfg=gc -Raw (Join-Path $out 'config.json')|ConvertFrom-Json;$ct=gc -Raw (Join-Path $out 'physics-contract.json')|ConvertFrom-Json;$raw=gc -Raw (Join-Path $out 'raw-responses.json')|ConvertFrom-Json;$rs=gc -Raw (Join-Path $out 'results.json')|ConvertFrom-Json;$mf=gc -Raw (Join-Path $out 'manifest.json')|ConvertFrom-Json
Req($mf.schema-eq'wp3-manifest-v2'-and$mf.status-eq'Passed')'manifest schema/status';Req($mf.evidence_class-eq'Synthetic-run/Reference-regression')'evidence'
Req($ct.schema-eq'wp3-physics-contract-v1'-and$ct.required_cases.Count-eq5-and$ct.wfem_device-eq'axial_grounded_electric_dipole')'minimum contract'
Req($ct.relative_tolerance-eq1e-6-and$ct.diffusion.conductive_ratio_min-eq100-and$ct.diffusion.air_branch-eq'full_maxwell')'contract downgrade'
foreach($name in @('dc_halfspace','mt_1d','tem_halfspace','csamt_finite_source','wfem_axial')){Req($ct.case_tolerances.$name.relative-le2e-5-and-not[string]::IsNullOrWhiteSpace($ct.case_tolerances.$name.source))"case tolerance $name"}
Req($ct.case_tolerances.tem_halfspace.source-ceq'empymod==2.6.0 DLF key_201_2012; 5-point Gauss gate average; late-time -5/2 slope and finite-ramp/step convergence')'TEM tolerance source';Req($ct.case_tolerances.csamt_finite_source.source-ceq'empymod==2.6.0 finite bipole DLF; near/transition/far complex E/H and 100 ohm-m far-field limit')'CSAMT tolerance source';Req($ct.case_tolerances.wfem_axial.source-ceq'empymod==2.6.0 finite bipole DLF versus QWE transform cross-check; signed ABMN DC invariant')'WFEM tolerance source'
foreach($f in $mf.files.PSObject.Properties){Req((Get-FileHash -Algorithm SHA256 (Join-Path $out $f.Name)).Hash.ToLowerInvariant()-eq$f.Value)"file hash $($f.Name)"}
foreach($s in $mf.sources.PSObject.Properties){Req((Get-FileHash -Algorithm SHA256 (Join-Path $toy $s.Name)).Hash.ToLowerInvariant()-eq$s.Value)"source hash $($s.Name)"}
$runnerText=gc -Raw (Join-Path $toy 'run-wp3-physics.ps1');$oracleText=gc -Raw (Join-Path $toy 'oracle/wp3-oracle.ps1');Req($runnerText-match'CsamtEKernel'-and$runnerText-match'CsamtHKernel'-and$runnerText-notmatch'\$h\s*=\s*\$e\s*/\s*\$z')'CSAMT direct E/H independence';Req($oracleText-match'AdaptiveComplex'-and$oracleText-notmatch'function\s+Green'-and$oracleText-notmatch'Pow\(\$t\s*,\s*-2\.5')'oracle algorithm independence'
Req(-not($cfg.tem.PSObject.Properties.Name-ccontains'characteristic_loop_length_m'))'independent TEM loop length rejected'
foreach($v in @($cfg.medium.sigma_s_m,$cfg.medium.epsilon_f_m,$cfg.medium.mu_h_m,$cfg.tem.current_a,$cfg.tem.equivalent_transmitter_area_m2,$cfg.tem.equivalent_receiver_area_m2,$cfg.tem.transmitter_turns,$cfg.tem.receiver_turns,$cfg.tem.loop_depth_m,$cfg.tem.ramp_s,$cfg.tem.gate_quadrature_order,$cfg.tem.small_loop_domain.ratio_max,$cfg.csamt.frequency_hz,$cfg.csamt.current_a,$cfg.csamt.electrode_depth_m,$cfg.csamt.source_depth_m,$cfg.csamt.receiver_z_m,$cfg.wfem.frequency_hz,$cfg.wfem.current_a,$cfg.dc.rho_ohm_m,$cfg.dc.current_a,$cfg.dc.am_m,$cfg.dc.an_m,$cfg.dc.bm_m,$cfg.dc.bn_m,$cfg.mt.rho_ohm_m,$cfg.mt.frequency_hz,$cfg.rock_fixture.temperature_k,$cfg.rock_fixture.curie_temperature_k,$cfg.rock_fixture.confining_pressure_pa,$cfg.rock_fixture.pore_pressure_pa)){Req(FinitePositive $v)'finite positive input domain'}
foreach($v in @($cfg.csamt.a_m,$cfg.csamt.b_m,$cfg.wfem.a_m,$cfg.wfem.b_m,$cfg.wfem.m_m,$cfg.wfem.n_m)){Req([double]::IsFinite([double]$v))'finite geometry domain'}
Req(@($cfg.rock_fixture.PSObject.Properties.Name|Where-Object{$_-match'(?i)temperature_c|celsius|degc'}).Count-eq0)'machine Celsius rejected'
foreach($b in @('induced_dominant','magnetization_known','low_latitude','stable_strike','local_threshold_calibrated')){Req($cfg.decisions.$b-is[bool])"decision boolean domain $b"};Req($cfg.decisions.mt_dimension-in@('2d','3d'))'MT dimension enum domain'
Req(@($cfg.tem.times_s|?{-not(FinitePositive $_)-or[double]$_-le[double]$cfg.tem.ramp_s}).Count-eq0)'TEM domain'
Req(@($cfg.tem.quadrature_levels+$cfg.csamt.quadrature_levels|?{-not(FinitePositive $_)-or[double]$_-ne[int]$_-or[int]$_-lt2}).Count-eq0-and[double]$cfg.tem.gate_quadrature_order-eq[int]$cfg.tem.gate_quadrature_order)'integration domain'
foreach($g in @($cfg.tem.gates_s+$cfg.tem.asymptotic_check.gates_s)){Req($g.Count-eq2-and(FinitePositive $g[0])-and(FinitePositive $g[1])-and[double]$g[1]-gt[double]$g[0]-and[double]$g[0]-gt[double]$cfg.tem.ramp_s)'TEM gate domain'}
foreach($x in $cfg.csamt.receiver_x_m){Req([double]::IsFinite([double]$x)-and[double]$x-gt[double]$cfg.csamt.b_m)'CSAMT receiver domain'}
Req([double]$cfg.csamt.a_m-ne[double]$cfg.csamt.b_m-and[double]$cfg.wfem.a_m-ne[double]$cfg.wfem.b_m-and[double]$cfg.wfem.m_m-ne[double]$cfg.wfem.n_m)'geometry domain'
$conductiveRatio=[double]$cfg.medium.sigma_s_m/(2*[Math]::PI*[double]$cfg.csamt.frequency_hz*[double]$cfg.medium.epsilon_f_m);Req([double]::IsFinite($conductiveRatio)-and$conductiveRatio-ge[double]$ct.diffusion.conductive_ratio_min)'diffusion gate before empymod'
$tMin=[double](($cfg.tem.gates_s|%{[double]$_[0]}|Measure-Object -Minimum).Minimum);$deltaPre=[Math]::Sqrt(4*$tMin/([double]$cfg.medium.mu_h_m*[double]$cfg.medium.sigma_s_m));$txLength=[Math]::Sqrt([double]$cfg.tem.equivalent_transmitter_area_m2/[Math]::PI);$rxLength=[Math]::Sqrt([double]$cfg.tem.equivalent_receiver_area_m2/[Math]::PI);$loopLength=[Math]::Max($txLength,$rxLength);$loopRatioPre=$loopLength/$deltaPre;Req($cfg.tem.small_loop_domain.ratio_definition-ceq'max(sqrt(A_tx/pi),sqrt(A_rx/pi))/delta_diff(t_min)'-and(FinitePositive $cfg.tem.small_loop_domain.ratio_max)-and[double]::IsFinite($loopRatioPre)-and$loopRatioPre-le[double]$cfg.tem.small_loop_domain.ratio_max)'small-loop gate before empymod'
$op=Join-Path ([IO.Path]::GetTempPath())('wp3-empymod-'+[guid]::NewGuid().ToString('N')+'.json');$oracleExe=Join-Path $toy '.venv-oracle/Scripts/python.exe';$oracleScript=Join-Path $toy 'oracle/empymod-frequency-oracle.py';try{& $oracleExe $oracleScript --config (Join-Path $out 'config.json') --output $op *> $null;Req($LASTEXITCODE-eq0-and(Test-Path $op))'empymod oracle exit/output';$o=gc -Raw $op|ConvertFrom-Json;Req($o.empymod_version-eq'2.6.0')'empymod version'}finally{if(Test-Path $op){Remove-Item $op}}
$rt=[double]$ct.relative_tolerance;$rtDc=[double]$ct.case_tolerances.dc_halfspace.relative;$rtMt=[double]$ct.case_tolerances.mt_1d.relative;$rtTem=[double]$ct.case_tolerances.tem_halfspace.relative;$rtCs=[double]$ct.case_tolerances.csamt_finite_source.relative;$rtWf=[double]$ct.case_tolerances.wfem_axial.relative;$dcRef=[double]$cfg.dc.rho_ohm_m/(2*[Math]::PI)*(1/[double]$cfg.dc.am_m-1/[double]$cfg.dc.an_m-1/[double]$cfg.dc.bm_m+1/[double]$cfg.dc.bn_m);$mtRef=[Numerics.Complex]::Sqrt([Numerics.Complex]::new(0,2*[Math]::PI*[double]$cfg.mt.frequency_hz*[double]$cfg.medium.mu_h_m*[double]$cfg.mt.rho_ohm_m));Req(Near $raw.dc.re $dcRef $rtDc)'DC mismatch';Req((Near $raw.mt.re $mtRef.Real $rtMt)-and(Near $raw.mt.im $mtRef.Imaginary $rtMt))'MT mismatch'
Req($raw.reference_engine-eq'empymod==2.6.0/dlf'-and$raw.tem_device-eq'magnetic-dipole/small-loop approximation'-and$raw.tem.Count-eq$o.tem_magnetic_dipole_small_loop_gate_average.Count)'TEM engine/count';$dd=[Math]::Sqrt(4*[double]$raw.small_loop_domain.t_min_s/([double]$cfg.medium.mu_h_m*[double]$cfg.medium.sigma_s_m));Req((Near $raw.small_loop_domain.delta_diff_m $dd 1e-12)-and(Near $raw.small_loop_domain.tx_characteristic_length_m $txLength 1e-12)-and(Near $raw.small_loop_domain.rx_characteristic_length_m $rxLength 1e-12)-and(Near $raw.small_loop_domain.characteristic_loop_length_m $loopLength 1e-12)-and(Near $raw.small_loop_domain.ratio ($loopLength/$dd) 1e-12)-and[double]$raw.small_loop_domain.ratio-le[double]$cfg.tem.small_loop_domain.ratio_max)'TEM small-loop domain';for($i=0;$i-lt$o.tem_magnetic_dipole_small_loop_gate_average.Count;$i++){Req((Near $raw.tem[$i].step_gate_average_v $o.tem_magnetic_dipole_small_loop_gate_average[$i].step_gate_average_v $rtTem)-and(Near $raw.tem[$i].ramp_gate_average_v $o.tem_magnetic_dipole_small_loop_gate_average[$i].ramp_gate_average_v $rtTem))'TEM gate average';Req([double]$raw.tem[$i].gate_stop_s-gt[double]$raw.tem[$i].gate_start_s-and$raw.tem[$i].nodes_s.Count-eq[int]$cfg.tem.gate_quadrature_order)'TEM gate metadata'};Req([double]$raw.tem[0].step_gate_average_v-gt[double]$raw.tem[1].step_gate_average_v-and[double]$raw.tem[1].step_gate_average_v-gt[double]$raw.tem[2].step_gate_average_v)'TEM early/late trend'
Req($raw.tem_asymptotic.Count-eq$o.tem_magnetic_dipole_late_time_asymptotic_gate_average.Count-and-not[string]::IsNullOrWhiteSpace([string]$cfg.tem.asymptotic_check.slope_tolerance_source)-and-not[string]::IsNullOrWhiteSpace([string]$cfg.tem.asymptotic_check.ratio_tolerance_source))'TEM asymptotic registration';for($i=0;$i-lt$raw.tem_asymptotic.Count;$i++){Req((Near $raw.tem_asymptotic[$i].step_gate_average_v $o.tem_magnetic_dipole_late_time_asymptotic_gate_average[$i].step_gate_average_v $rtTem)-and(Near $raw.tem_asymptotic[$i].ramp_gate_average_v $o.tem_magnetic_dipole_late_time_asymptotic_gate_average[$i].ramp_gate_average_v $rtTem))'TEM asymptotic raw';Req($raw.tem_asymptotic[$i].nodes_s.Count-eq[int]$cfg.tem.gate_quadrature_order)'TEM asymptotic nodes'};$fit=@($cfg.tem.asymptotic_check.fit_gate_indices|%{[int]$_});$slope=LogSlope $raw.tem_asymptotic $fit;Req([Math]::Abs($slope-[double]$cfg.tem.asymptotic_check.slope_target)-le[double]$cfg.tem.asymptotic_check.slope_absolute_tolerance)'TEM late-time -5/2 slope';$prev=[double]::PositiveInfinity;foreach($i in $fit){$e=[Math]::Abs([double]$raw.tem_asymptotic[$i].ramp_gate_average_v/[double]$raw.tem_asymptotic[$i].step_gate_average_v-1);Req($e-lt$prev)'TEM ramp/step convergence trend';$prev=$e};Req($prev-le[double]$cfg.tem.asymptotic_check.ramp_step_ratio_terminal_absolute_tolerance)'TEM ramp/step terminal convergence'
Req($raw.csamt.Count-eq$o.csamt.Count)'CSAMT count';for($i=0;$i-lt$o.csamt.Count;$i++){Req((Near $raw.csamt[$i].ex.re $o.csamt[$i].ex.re $rtCs)-and(Near $raw.csamt[$i].ex.im $o.csamt[$i].ex.im $rtCs)-and(Near $raw.csamt[$i].hy.re $o.csamt[$i].hy.re $rtCs)-and(Near $raw.csamt[$i].hy.im $o.csamt[$i].hy.im $rtCs)-and(Near $raw.csamt[$i].rho_a $o.csamt[$i].rho_a_ohm_m $rtCs)-and(Near $raw.csamt[$i].phase_rad $o.csamt[$i].phase_rad $rtCs))"CSAMT empymod $i"};Req(($raw.csamt.region-join'|')-eq'near|transition|far')'CSAMT regions';Req([Math]::Abs([double]$raw.csamt[-1].rho_a-1/[double]$cfg.medium.sigma_s_m)-le1.0)'CSAMT far halfspace limit'
$wfD=$o.wfem_delta_u_over_i_ohm.dlf;$wfQ=$o.wfem_delta_u_over_i_ohm.qwe;Req((Near $raw.wfem.re $wfD.re $rtWf)-and(Near $raw.wfem.im $wfD.im $rtWf))'WFEM empymod DLF';Req((Near $wfD.re $wfQ.re 2e-5)-and(Near $wfD.im $wfQ.im 2e-5))'WFEM DLF/QWE cross-transform'
$wfDen=1/[Math]::Abs([double]$cfg.wfem.m_m-[double]$cfg.wfem.a_m)-1/[Math]::Abs([double]$cfg.wfem.n_m-[double]$cfg.wfem.a_m)-1/[Math]::Abs([double]$cfg.wfem.m_m-[double]$cfg.wfem.b_m)+1/[Math]::Abs([double]$cfg.wfem.n_m-[double]$cfg.wfem.b_m);Req(([Math]::Sign([double]$raw.wfem.geometric_factor_m))-eq([Math]::Sign(2*[Math]::PI/$wfDen)))'WFEM signed K'
$wfCx=[Numerics.Complex]::new([double]$raw.wfem.re,[double]$raw.wfem.im);$wfApp=[double]$raw.wfem.geometric_factor_m*$wfCx;Req((Near $raw.wfem.apparent_complex.re $wfApp.Real $rtWf)-and(Near $raw.wfem.apparent_complex.im $wfApp.Imaginary $rtWf)-and(Near $raw.wfem.rho_a_ohm_m $wfApp.Magnitude $rtWf)-and(Near $raw.wfem.phase_rad $wfApp.Phase $rtWf))'WFEM signed derived consistency'
$ratio=[double]$cfg.medium.sigma_s_m/(2*[Math]::PI*[double]$cfg.csamt.frequency_hz*[double]$cfg.medium.epsilon_f_m);Req($ratio-ge100-and$rs.branch.solver-eq'diffusion'-and(Near $rs.branch.conductive_ratio $ratio 1e-12))'diffusion applicability'
$mexp=1/(1+[Math]::Exp(-[double]$cfg.rock_fixture.tdip_logit));$tauexp=[Math]::Exp([double]$cfg.rock_fixture.tau_log_s);$seexp=[double]$cfg.rock_fixture.confining_pressure_pa-[double]$cfg.rock_fixture.biot_alpha*[double]$cfg.rock_fixture.pore_pressure_pa;Req((Near $rs.rock.m $mexp 1e-12)-and(Near $rs.rock.tau_s $tauexp 1e-12)-and(Near $rs.rock.effective_stress_pa $seexp 1e-12))'rock calculation';$rexp=if($cfg.decisions.induced_dominant-and$cfg.decisions.magnetization_known-and-not$cfg.decisions.low_latitude){'publish_rtp'}else{'alternative_magnetization'};$mtexp=if($cfg.decisions.mt_dimension-eq'2d'-and$cfg.decisions.stable_strike){'publish_2d'}else{'publish_3d_tensor'};$thexp=if($cfg.decisions.local_threshold_calibrated-and[int]$cfg.decisions.competing_explanations_count-ge1){'publish_calibrated'}else{'local_calibration_required'};Req($rs.decisions.rtp-eq$rexp-and$rs.decisions.mt-eq$mtexp-and$rs.decisions.threshold-eq$thexp)'decision branches'
$docs=@('01-引言.md','02-全方法深度融合的底层逻辑与理论总纲.md','06-合成数据验证方案与验收设计.md','附录1-分矿种多方法融合定制化勘查模板.md','附录11-分勘查阶段标准化操作手册.md','附录13-岩性物性参数统计数据库.md','附录14-地质先验知识库.md');$text=@{};foreach($d in $docs){$text[$d]=gc -Raw (Join-Path $root $d)}
$d02=$text[$docs[1]];foreach($pat in @('Pi_\{near\}','Pi_\{static\}','15%-30%','10°-20°','K_\{WFEM\}','r\s*>\s*\(3\s*\\sim\s*6\)')){Req(-not($d02-match$pat))"forbidden $pat"}
Req($text[$docs[0]].Contains('不是严格探测深度')-and$text[$docs[2]].Contains('WP3预注册物理回归矩阵'))'01/06 closure';Req($text[$docs[3]].Contains('WP3逐表发布门'))'appendix1 closure';Req($text[$docs[4]].Contains('低磁纬稳定性门')-and$text[$docs[4]].Contains('强制3D'))'RTP/MT';Req($text[$docs[5]].Contains('0<m<1')-and$text[$docs[5]].Contains('T>T_C')-and$text[$docs[5]].Contains('sigma_{\rm eff}'))'rock';Req($text[$docs[6]].Contains('WP3区内校准'))'prior closure'
foreach($gate in @(@($docs[2],7),@($docs[3],9),@($docs[4],7),@($docs[6],5))){$count=[regex]::Matches($text[$gate[0]],'WP3-SECTION-STATUS id=[^\s]+ status=Design-assumption gate=[^\s]+').Count;Req($count-ge[int]$gate[1])"section publication gates $($gate[0])"}
foreach($docName in @($docs[2],$docs[3],$docs[4],$docs[6])){$docLines=$text[$docName]-split"\r?\n";for($i=0;$i-lt$docLines.Count;$i++){if($docLines[$i]-match'^<!-- WP3-SECTION-STATUS '){$j=$i-1;while($j-ge0-and[string]::IsNullOrWhiteSpace($docLines[$j])){$j--};Req($j-ge0-and$docLines[$j]-match'^#{1,6}\s+\S')"section marker adjacency $docName line $($i+1)"}}}
if(-not$SkipSignoff-and-not$SelfTest){$sg=gc -Raw -LiteralPath (Join-Path $root 'WP3-地球物理与岩石物理独立签核.md');$fields=ParseSignoff $sg;$lines=ReadSignoffRoot (Join-Path $root 'WP3-signoff-input-root.sha256');foreach($line in $lines){$h=$line.Substring(0,64);$name=$line.Substring(66);$actual=if($name-ceq'ACTIVE_MANIFEST'){(Get-FileHash -Algorithm SHA256 (Join-Path $out 'manifest.json')).Hash.ToLowerInvariant()}else{(Get-FileHash -Algorithm SHA256 (Join-Path $root $name)).Hash.ToLowerInvariant()};Req($actual-ceq$h)"signoff root drift $name"};$joined=($lines-join"`n")+"`n";$sha=[Security.Cryptography.SHA256]::Create();try{$memberRoot=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($joined)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};$fileRoot=(Get-FileHash -Algorithm SHA256 (Join-Path $root 'WP3-signoff-input-root.sha256')).Hash.ToLowerInvariant();$manifestHash=(Get-FileHash -Algorithm SHA256 (Join-Path $out 'manifest.json')).Hash.ToLowerInvariant();Req($fields['状态']-ceq'PASS')'independent signoff Pending';Req($fields['成员清单内容根SHA-256']-ceq$memberRoot)'signoff member-content root';Req($fields['根清单文件SHA-256']-ceq$fileRoot)'signoff root-file hash';Req($fields['输入版本']-ceq[string]$mf.run_instance_id)'signoff version';Req($fields['manifest SHA-256']-ceq$manifestHash)'signoff manifest'}
if($SelfTest){$cases=@('raw_tem','raw_tem_slope','raw_tem_ratio_trend','raw_csamt','raw_wfem','geometry','waveform','contract','source');$n=0;$exe=(Get-Process -Id $PID).Path;foreach($c in $cases){$tmp=Join-Path ([IO.Path]::GetTempPath())('wp3-fixture-'+[guid]::NewGuid().ToString('N'));Copy-Item -Recurse $out $tmp;try{if($c-like'raw_*'){$f=Join-Path $tmp 'raw-responses.json';$x=gc -Raw $f|ConvertFrom-Json;if($c-eq'raw_tem'){$x.tem[0].step_gate_average_v*=2}elseif($c-eq'raw_tem_slope'){$x.tem_asymptotic[4].step_gate_average_v*=2}elseif($c-eq'raw_tem_ratio_trend'){$x.tem_asymptotic[4].ramp_gate_average_v=$x.tem_asymptotic[4].step_gate_average_v*1.02}elseif($c-eq'raw_csamt'){$x.csamt[0].ex.re*=2}else{$x.wfem.re*=2};$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $f}elseif($c-in@('geometry','waveform')){$f=Join-Path $tmp 'config.json';$x=gc -Raw $f|ConvertFrom-Json;if($c-eq'geometry'){$x.wfem.n_m=$x.wfem.m_m}else{$x.tem.ramp_s=$x.tem.times_s[0]};$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $f}elseif($c-eq'contract'){$f=Join-Path $tmp 'physics-contract.json';$x=gc -Raw $f|ConvertFrom-Json;$x.relative_tolerance=.5;$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $f}else{$mf.sources.'run-wp3-physics.ps1'='0'*64};$m=gc -Raw (Join-Path $tmp 'manifest.json')|ConvertFrom-Json;foreach($p in $m.files.PSObject.Properties){$p.Value=(Get-FileHash -Algorithm SHA256 (Join-Path $tmp $p.Name)).Hash.ToLowerInvariant()};if($c-eq'source'){$m.sources.'run-wp3-physics.ps1'='0'*64};$m|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 (Join-Path $tmp 'manifest.json'); & $exe -NoProfile -File $MyInvocation.MyCommand.Path -OutputOverride $tmp -SkipSignoff *>$null;if($LASTEXITCODE-ne0){$n++}}finally{Remove-Item -Recurse -Force $tmp}};Req($n-eq$cases.Count)"SelfTest $n/$($cases.Count)"}
if($SelfTest){
 $extra=@('unit','override_large_area','override_nan_ratio','override_dc','override_mt','override_loop_field','override_string_false','override_bad_dimension','branch','rock','decision','tolerance_source','tem_levels','csamt_levels','wfem_derived');$caught=0;$exe=(Get-Process -Id $PID).Path
 foreach($c in $extra){
  $tmp=Join-Path ([IO.Path]::GetTempPath())('wp3-extra-'+[guid]::NewGuid().ToString('N'));Copy-Item -Recurse $out $tmp
  try{
   if($c-in@('unit','override_large_area','override_nan_ratio','override_dc','override_mt','override_loop_field','override_string_false','override_bad_dimension')){$f=Join-Path $tmp 'config.json';$x=gc -Raw $f|ConvertFrom-Json;if($c-eq'unit'){$x.medium.sigma_s_m=-1}elseif($c-eq'override_large_area'){$x.tem.equivalent_transmitter_area_m2=30000}elseif($c-eq'override_nan_ratio'){$x.tem.small_loop_domain.ratio_max='NaN'}elseif($c-eq'override_dc'){$x.dc.rho_ohm_m=0}elseif($c-eq'override_mt'){$x.mt.frequency_hz='NaN'}elseif($c-eq'override_loop_field'){$x.tem|Add-Member -NotePropertyName characteristic_loop_length_m -NotePropertyValue 1}elseif($c-eq'override_string_false'){$x.decisions.low_latitude='false'}else{$x.decisions.mt_dimension='1d'}}
   elseif($c-eq'tolerance_source'){$f=Join-Path $tmp 'physics-contract.json';$x=gc -Raw $f|ConvertFrom-Json;$x.case_tolerances.tem_halfspace.source='midpoint_128_vs_analytic_ramp';$x.case_tolerances.csamt_finite_source.source='midpoint_128_vs_endpoint_antiderivative'}
   elseif($c-in@('branch','rock','decision')){$f=Join-Path $tmp 'results.json';$x=gc -Raw $f|ConvertFrom-Json;if($c-eq'branch'){$x.branch.solver='full_maxwell'}elseif($c-eq'rock'){$x.rock.m=.99}else{$x.decisions.rtp='publish_rtp'}}
   else{$f=Join-Path $tmp 'raw-responses.json';$x=gc -Raw $f|ConvertFrom-Json;if($c-eq'tem_levels'){$x.tem[0].ramp_gate_average_v*=2}elseif($c-eq'csamt_levels'){$x.csamt[0].hy.re*=2}else{$x.wfem.rho_a_ohm_m*=2}}
   $x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $f
   $m=gc -Raw (Join-Path $tmp 'manifest.json')|ConvertFrom-Json;foreach($p in $m.files.PSObject.Properties){$p.Value=(Get-FileHash -Algorithm SHA256 (Join-Path $tmp $p.Name)).Hash.ToLowerInvariant()};$m|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 (Join-Path $tmp 'manifest.json')
   & $exe -NoProfile -File $MyInvocation.MyCommand.Path -OutputOverride $tmp -SkipSignoff *>$null;if($LASTEXITCODE-ne0){$caught++}
  }finally{Remove-Item -Recurse -Force $tmp}
 }
 Req($caught-eq$extra.Count)"SelfTest-extra $caught/$($extra.Count)"
}
if($SelfTest){
 $iso=Join-Path ([IO.Path]::GetTempPath())('wp3-isolated-toy-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $iso|Out-Null;New-Item -ItemType Directory (Join-Path $iso 'oracle')|Out-Null
 try{
  foreach($f in @('config.json','physics-contract.json','run-wp3-physics.ps1','active-output.json')){Copy-Item (Join-Path $toy $f) $iso};Copy-Item (Join-Path $toy 'oracle/*') (Join-Path $iso 'oracle');New-Item -ItemType Junction -Path (Join-Path $iso '.venv-oracle') -Target (Join-Path $toy '.venv-oracle')|Out-Null;$seedPtr=ReadJsonRetry (Join-Path $toy 'active-output.json');$seedDest=Join-Path $iso $seedPtr.version_path;New-Item -ItemType Directory (Split-Path -Parent $seedDest)|Out-Null;Copy-Item -Recurse (Join-Path $toy $seedPtr.version_path) $seedDest
  $runner=Join-Path $iso 'run-wp3-physics.ps1';$active=Join-Path $iso 'active-output.json';$before=(Get-FileHash -Algorithm SHA256 $active).Hash
  $orphanId='19990101T000000000Z-'+[guid]::NewGuid().ToString('N');$orphan=Join-Path $iso ('versions/'+$orphanId);New-Item -ItemType Directory $orphan|Out-Null;Set-Content -Encoding utf8 (Join-Path $iso '.publish-journal.json') ('{"schema":"wp3-publish-journal-v1","version_path":"versions/'+$orphanId+'"}')
  $assertPointer={param($label)$pp=ReadJsonRetry $active;$mp=Join-Path $iso ($pp.version_path+'/manifest.json');Req((Test-Path $mp)-and(Get-FileHash -Algorithm SHA256 $mp).Hash.ToLowerInvariant()-eq$pp.manifest_sha256)"pointer/manifest mismatch $label"};$reads=0;&$assertPointer 'pre-publish';$reads++
  & (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;$publishExit=$LASTEXITCODE;Req($publishExit-eq0)'publisher exit';&$assertPointer 'post-publish';$reads++;Req($reads-eq2-and-not(Test-Path $orphan)-and-not(Test-Path (Join-Path $iso '.publish-journal.json')))'journal/orphan/pre-post consistency recovery'
  $before=(Get-FileHash -Algorithm SHA256 $active).Hash;foreach($flag in @('-InjectWorkerFailure','-InjectPublishInterruption')){& (Get-Process -Id $PID).Path -NoProfile -File $runner $flag *> $null;Req($LASTEXITCODE-ne0)"publish fixture $flag";Req((Get-FileHash -Algorithm SHA256 $active).Hash-eq$before)"isolated active changed $flag"}
  Set-Content -Encoding utf8 (Join-Path $iso '.publish-journal.json') '{';& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-ne0-and(Test-Path (Join-Path $iso '.publish-journal.json')))'truncated journal accepted';Remove-Item -Force (Join-Path $iso '.publish-journal.json')
  $sentinel=Join-Path $iso 'journal-sentinel';New-Item -ItemType Directory $sentinel|Out-Null;Set-Content -Encoding utf8 (Join-Path $sentinel 'keep.txt') 'keep';$activeVersion=(ReadJsonRetry $active).version_path
  foreach($case in @('absolute','parent','separator','active','unknown_field','unknown_schema')){$j=if($case-eq'absolute'){@{schema='wp3-publish-journal-v1';version_path=$sentinel}}elseif($case-eq'parent'){@{schema='wp3-publish-journal-v1';version_path='versions/../journal-sentinel'}}elseif($case-eq'separator'){@{schema='wp3-publish-journal-v1';version_path='versions/19990101T000000000Z-00000000000000000000000000000000/extra'}}elseif($case-eq'active'){@{schema='wp3-publish-journal-v1';version_path=$activeVersion}}elseif($case-eq'unknown_field'){@{schema='wp3-publish-journal-v1';version_path='versions/19990101T000000000Z-00000000000000000000000000000000';extra='bad'}}else{@{schema='wp3-publish-journal-v2';version_path='versions/19990101T000000000Z-00000000000000000000000000000000'}};$j|ConvertTo-Json -Compress|Set-Content -Encoding utf8 (Join-Path $iso '.publish-journal.json');$beforeJournalActive=(Get-FileHash -Algorithm SHA256 $active).Hash;& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-ne0-and(Test-Path (Join-Path $sentinel 'keep.txt'))-and(Get-FileHash -Algorithm SHA256 $active).Hash-eq$beforeJournalActive)"unsafe journal accepted $case";Remove-Item -Force (Join-Path $iso '.publish-journal.json')}
  $ptrBackup=Join-Path $iso 'pointer.backup';Copy-Item $active $ptrBackup;try{Set-Content -Encoding utf8 $active '{"schema":';$rejected=$false;try{$null=ReadJsonRetry $active}catch{$rejected=$true};Req($rejected)'truncated pointer accepted'}finally{Copy-Item -Force $ptrBackup $active;Remove-Item $ptrBackup}
  $cfgPath=Join-Path $iso 'config.json';$cfgBackup=Join-Path $iso 'config.backup';Copy-Item $cfgPath $cfgBackup
  foreach($case in @('low_ratio','celsius')){$x=gc -Raw $cfgBackup|ConvertFrom-Json;if($case-eq'low_ratio'){$x.medium.epsilon_f_m=1}else{$x.rock_fixture|Add-Member -NotePropertyName temperature_c -NotePropertyValue 25};$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $cfgPath;$old=(Get-FileHash -Algorithm SHA256 $active).Hash;& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-ne0-and(Get-FileHash -Algorithm SHA256 $active).Hash-eq$old)"runner reject $case"};Copy-Item -Force $cfgBackup $cfgPath
  & (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;$bp=ReadJsonRetry $active;$baseWf=(gc -Raw (Join-Path $iso ($bp.version_path+'/raw-responses.json'))|ConvertFrom-Json).wfem
  $baseRaw=gc -Raw (Join-Path $iso ($bp.version_path+'/raw-responses.json'))|ConvertFrom-Json
  $x=gc -Raw $cfgBackup|ConvertFrom-Json;$x.tem.current_a*=2;$x.tem.transmitter_turns*=2;$x.csamt.current_a*=2;$x.csamt.electrode_depth_m=.02;$x.csamt.source_depth_m=.02;$x.csamt.receiver_z_m=.02;$x.csamt.receiver_x_m=@(200,800,10000);$x.tem.gates_s[0]=@(.00092,.00108);$x.decisions.induced_dominant=$true;$x.decisions.magnetization_known=$true;$x.decisions.low_latitude=$false;$x.decisions.mt_dimension='2d';$x.decisions.stable_strike=$true;$x.decisions.local_threshold_calibrated=$true;$x.rock_fixture.temperature_k=900;$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $cfgPath;& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-eq0)'legal sensitivity/positive branches run';$sp=ReadJsonRetry $active;$sensOut=Join-Path $iso $sp.version_path;$sensRaw=gc -Raw (Join-Path $sensOut 'raw-responses.json')|ConvertFrom-Json;$sensRs=gc -Raw (Join-Path $sensOut 'results.json')|ConvertFrom-Json;Req((Near $sensRaw.tem[1].step_gate_average_v (4*[double]$baseRaw.tem[1].step_gate_average_v) 2e-5)-and[double]$sensRaw.tem[0].step_gate_average_v-ne[double]$baseRaw.tem[0].step_gate_average_v)'TEM legal current/turn scaling and gate width';Req([double]$sensRaw.csamt[0].ex.re-ne[double]$baseRaw.csamt[0].ex.re-and$sensRs.decisions.rtp-eq'publish_rtp'-and$sensRs.decisions.mt-eq'publish_2d'-and$sensRs.decisions.threshold-eq'publish_calibrated'-and$sensRs.rock.curie_branch-eq'curie_weiss')'CSAMT sensitivity/positive decisions';Copy-Item -Force $cfgBackup $cfgPath
  foreach($case in @('zero_frequency','nan_distance','bad_level','bad_gate','bad_biot','bad_boolean','bad_dimension','singular_source','zero_sigma','nan_time','tau_overflow','wfem_source_degenerate','small_loop_domain','nan_ratio_max','zero_dc_rho','nan_dc_distance','zero_mt_frequency','nan_mt_rho','independent_loop_length')){$x=gc -Raw $cfgBackup|ConvertFrom-Json;switch($case){'zero_frequency'{$x.csamt.frequency_hz=0};'nan_distance'{$x.csamt.receiver_x_m[0]='NaN'};'bad_level'{$x.csamt.quadrature_levels[0]=1};'bad_gate'{$x.tem.gates_s[0]=@(.0011,.0009)};'bad_biot'{$x.rock_fixture.biot_alpha=1.2};'bad_boolean'{$x.decisions.low_latitude='false'};'bad_dimension'{$x.decisions.mt_dimension='1d'};'singular_source'{$x.csamt.b_m=$x.csamt.a_m};'zero_sigma'{$x.medium.sigma_s_m=0};'nan_time'{$x.tem.times_s[0]='NaN'};'tau_overflow'{$x.rock_fixture.tau_log_s=1000};'wfem_source_degenerate'{$x.wfem.b_m=$x.wfem.a_m};'small_loop_domain'{$x.tem.equivalent_transmitter_area_m2=30000};'nan_ratio_max'{$x.tem.small_loop_domain.ratio_max='NaN'};'zero_dc_rho'{$x.dc.rho_ohm_m=0};'nan_dc_distance'{$x.dc.am_m='NaN'};'zero_mt_frequency'{$x.mt.frequency_hz=0};'nan_mt_rho'{$x.mt.rho_ohm_m='NaN'};'independent_loop_length'{$x.tem|Add-Member -NotePropertyName characteristic_loop_length_m -NotePropertyValue 1}};$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $cfgPath;& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-ne0)"edge accepted $case"};Copy-Item -Force $cfgBackup $cfgPath
  foreach($case in @('mn_exchange','ab_reciprocity')){$x=gc -Raw $cfgBackup|ConvertFrom-Json;if($case-eq'mn_exchange'){$q=$x.wfem.m_m;$x.wfem.m_m=$x.wfem.n_m;$x.wfem.n_m=$q}else{$q=$x.wfem.a_m;$x.wfem.a_m=$x.wfem.b_m;$x.wfem.b_m=$q};$x|ConvertTo-Json -Depth 12|Set-Content -Encoding utf8 $cfgPath;& (Get-Process -Id $PID).Path -NoProfile -File $runner *> $null;Req($LASTEXITCODE-eq0)"WFEM $case run";$sp=ReadJsonRetry $active;$sr=gc -Raw (Join-Path $iso ($sp.version_path+'/raw-responses.json'))|ConvertFrom-Json;Req((Near $sr.wfem.re (-[double]$baseWf.re) 1e-12)-and(Near $sr.wfem.im (-[double]$baseWf.im) 1e-12)-and(Near $sr.wfem.geometric_factor_m (-[double]$baseWf.geometric_factor_m) 1e-12)-and(Near $sr.wfem.apparent_complex.re $baseWf.apparent_complex.re 1e-12)-and(Near $sr.wfem.apparent_complex.im $baseWf.apparent_complex.im 1e-12))"WFEM signed invariant $case"}
 }finally{if(Test-Path $iso){$deadline=[DateTime]::UtcNow.AddSeconds(10);do{try{Remove-Item -Recurse -Force $iso -ErrorAction Stop;break}catch{if([DateTime]::UtcNow-ge$deadline){throw};Start-Sleep -Milliseconds 20}}while(Test-Path $iso)}}
}
if($SelfTest){
 $rootLines=ReadSignoffRoot (Join-Path $root 'WP3-signoff-input-root.sha256');$joined=($rootLines-join"`n")+"`n";$sha=[Security.Cryptography.SHA256]::Create();try{$mr=([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($joined)))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()};$fr=(Get-FileHash -Algorithm SHA256 (Join-Path $root 'WP3-signoff-input-root.sha256')).Hash.ToLowerInvariant();$ap=ReadJsonRetry (Join-Path $toy 'active-output.json');$ao=Join-Path $toy $ap.version_path;$mh=(Get-FileHash -Algorithm SHA256 (Join-Path $ao 'manifest.json')).Hash.ToLowerInvariant()
 $positive=@"
- 状态：PASS
- 输入版本：``$($ap.run_instance_id)``
- manifest SHA-256：``$mh``
- 成员清单内容根SHA-256：``$mr``
- 根清单文件SHA-256：``$fr``
"@;$pf=ParseSignoff $positive;Req($pf['状态']-ceq'PASS'-and$pf['输入版本']-ceq[string]$ap.run_instance_id-and$pf['manifest SHA-256']-ceq$mh-and$pf['成员清单内容根SHA-256']-ceq$mr-and$pf['根清单文件SHA-256']-ceq$fr)'correct strict signoff rejected'
 foreach($case in @('duplicate_status','replacement_status','duplicate_version','duplicate_manifest','duplicate_member_root','duplicate_file_root')){$bad=$positive;if($case-eq'duplicate_status'){$bad+="- 状态：PASS`n"}elseif($case-eq'replacement_status'){$bad=$bad.Replace('- 状态：PASS','说明：状态：PASS')}elseif($case-eq'duplicate_version'){$bad+="- 输入版本：``$($ap.run_instance_id)```n"}elseif($case-eq'duplicate_manifest'){$bad+="- manifest SHA-256：``$mh```n"}elseif($case-eq'duplicate_member_root'){$bad+="- 成员清单内容根SHA-256：``$mr```n"}else{$bad+="- 根清单文件SHA-256：``$fr```n"};$rejected=$false;try{$null=ParseSignoff $bad}catch{$rejected=$true};Req($rejected)"signoff parser fixture $case"}
 foreach($case in @('wrong_member_root','wrong_file_root','wrong_version','wrong_manifest')){$a=$mr;$b=$fr;$v=$ap.run_instance_id;$mhash=$mh;if($case-eq'wrong_member_root'){$a='0'*64}elseif($case-eq'wrong_file_root'){$b='0'*64}elseif($case-eq'wrong_version'){$v='bad-version'}else{$mhash='0'*64};$sf=@"
- 状态：PASS
- 输入版本：``$v``
- manifest SHA-256：``$mhash``
- 成员清单内容根SHA-256：``$a``
- 根清单文件SHA-256：``$b``
"@;$pf=ParseSignoff $sf;$rejected=($pf['成员清单内容根SHA-256']-cne$mr-or$pf['根清单文件SHA-256']-cne$fr-or$pf['输入版本']-cne[string]$ap.run_instance_id-or$pf['manifest SHA-256']-cne$mh);Req($rejected)"signoff binding fixture $case"}
}
"PASS run_id=$($cfg.run_id) self_test=$SelfTest";exit 0
